[package]
name = "leet_problems"
version = "0.1.0"
authors = ["Sercan Turkmen <sercan@alpaca.ai>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
